displayName=Clan QOL
author=Snape Grass
description=Clan chat interface enhancements
tags=clan,broadcast,rank,icon,chat,clanchat,filtering,filter,qol,notes,flags,timezones
version= 1.4.3
plugins=com.clanqol.ClanQolPlugin
build=standard
