displayName=Clan QOL
author=Snape Grass
description=Clan chat interface enhancements
tags=clan,broadcast,rank,icon,chat,clanchat,filtering,filter,qol,notes,flags,timezones
version= 1.3.0
plugins=com.betterclanbroadcasts.BetterClanBroadcastsPlugin
build=standard
