displayName=Clan QOL
author=Snape Grass
description=Clan chat interface enhancements
tags=clan,broadcast,rank,icon,chat,clanchat,filtering,filter,qol,notes
version= 1.2.2
plugins=com.betterclanbroadcasts.BetterClanBroadcastsPlugin
build=standard
